version: "3.8"

services:
  app:
    build: .
    container_name: gin-app
    ports:
      - "8090:8080"
    # volumes:
    #   - .:/app
    environment:
      - GO_ENV=development
    # command: ./app
